sudo: required
dist: trusty
language: node_js
node_js:
  - '7.7.4'

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install

script:
- npm run test -- --watch=false
- npm run e2e

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .
  - docker push $REPO

